# Generated by Django 5.0.4 on 2024-05-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_prescription_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoinment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appoinment',
            name='time',
        ),
        migrations.AddField(
            model_name='appoinment',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='datetime'),
        ),
    ]
