# Generated by Django 5.0.4 on 2024-05-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_appoinment_date_remove_appoinment_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appoinment',
            old_name='datetime',
            new_name='datetimes',
        ),
    ]
