# Generated by Django 5.0.4 on 2024-05-03 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='image',
            field=models.FileField(default=1, upload_to='hospital/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='file'),
            preserve_default=False,
        ),
    ]
