# Generated by Django 5.0.4 on 2024-05-06 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationotp',
            name='type',
        ),
    ]
