# Generated by Django 5.0.4 on 2024-05-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('doctor', 'doctor'), ('patient', 'patient'), ('admin', 'admin')], default='patient', max_length=10, verbose_name='role'),
        ),
    ]
