# Generated by Django 4.2.6 on 2024-05-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationotp',
            name='user',
        ),
        migrations.AddField(
            model_name='verificationotp',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='verificationotp',
            name='expires_in',
            field=models.DateTimeField(null=True, verbose_name='expires in'),
        ),
    ]
